### PR TITLE
Embed API

### PR DESCRIPTION
**Pull request by nasser**
This is an implementation of a basic embed API for Rubinius as originally [discussed here](http://donttreadonme.co.uk/rubinius-irc/rubinius.log.20110623.html). It builds on @gaffo's [work](https://github.com/gaffo/rubinius/commit/58da9169bbdfe875d9595696c5e381c71ecc2170) by implementing the methods he stubbed out and adding a few more where they were needed.

The code passed my informal `printf` tests, but testing it formally is difficult as the current implementation crashes when a Rubinius context is stopped and restarted. This makes running multiple isolated tests from one processes impossible at the moment. I'm testing by using [these files](https://gist.github.com/1128709) and statically linking to `librubinius-static.a` (generated from [my fork](https://github.com/nasser/rubinius/tree/librbx_osx_fix)). The program generates the following output.

```
** rbx_require_file
./req.rb required

** rbx_eval_file
a.rb
foo method called
caesar

** rbx_eval_file
b.rb
This is file b

** rbx_eval
Hello, World!
Hello, Woorld!
Hello, Wooorld!
Hello, Woooorld!
Hello, Wooooorld!
Hello, Woooooorld!
Hello, Wooooooorld!
Hello, Woooooooorld!
Hello, Wooooooooorld!
Hello, Woooooooooorld!
Hello, Wooooooooooorld!
```

This is a *very* early draft and everything is up in the air, subject to change. But it works well enough and I feel it is a good place to start the conversation around the nature of the API.

### CODE REVIEW

**Comment by chrisseaton** [comment]
#3446 will cause issues on Mac when embedded dynamically.

**Comment by brixen** [comment]
@nasser Thanks for your work on this. I'm still interested in making Rubinius embeddable, but there's a substantial amount of work that needs to be done initially and it's not very high priority due to very little demand.

I'm going to close this because it will need to be rewritten anyway and it hasn't seen any activity in a long time.

**Comment by nasser** [comment]
Understood!

**Comment by brixen** [comment]
@nasser for a bit more context, please see [this comment](https://github.com/rubinius/rubinius/issues/1851#issuecomment-167592988) from a related ticket. These two concepts (embedding and C++ API) are closely related and will likely end up under the same milestone.

**Pull request closed without merging**
