### PR TITLE
Regex new 2959

### LINKED ISSUE #2959: Error raised by Regexp.new(<integer>) differs between MRI and Rubinius
In MRI 1.9.3-p545:

```irb
1.9.3-p545 :001 > Regexp.new(123)
TypeError: can't convert Fixnum into String
```

In Rubinius 2.2.5:

```irb
rbx-2.2.5 :001 > Regexp.new(123)
PrimitiveFailure: Regexp.compile(123, 0) primitive failed
	from kernel/bootstrap/regexp.rb:13:in `compile'
	from kernel/common/regexp.rb:141:in `initialize'
	from (irb):1
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:460:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:649:in `script'
	from kernel/loader.rb:831:in `main'rbx-2.2.5 :002
```

This causes issues in https://github.com/limhoff-r7/metasploit-framework/blob/3d196cb399bb9a711427916d38c43cb3779624ae/lib/msf/core/option_container.rb#L485-L491 as I can't rescue PrimiteFailure since it's Rubinius specific.  

Should Regexp.new raising TypeError when passed an Integer be in RubySpec or is this considered implementation-specific behavior?

### PR DESCRIPTION
**Pull request by tak1n**
Not sure why @jc00ke commits were reverted, therefore opening this PR.

This closes #2959

### CODE REVIEW

**Comment by tak1n** [comment]
The error for the gcc build seems unrelated to the changes in the pr:

```
/home/travis/build/rubinius/rubinius/spec/ruby/optional/capi/thread_spec.rb                                               F
.
.
.

1)

C-API Thread function rb_thread_create handles throwing an exception in the thread FAILED

Expected NotImplementedError

but got TypeError (wrong argument type System (expected Array))
```

**Comment by jemc** [comment]
@tak1n - I restarted the CI build just now - as a `Collaborator` you should be able to restart it too with the button on the Travis-CI page for the built.

**Comment by jemc** [comment]
Looking at the git history, I'm not sure what happened, but maybe somebody force-pushed onto master and made @jc00ke's commits disappear.  Either way, I see no reason this shouldn't be merged.

If someone knows a reason why the commits were removed they can speak up and leave a better paper trail this time.

**Comment by tak1n** [comment]
awesome thx

**Comment by jc00ke** [comment]
Hmm, weird. Thanks for catching it @tak1n!

**Pull request merged**
