### PR TITLE
Enable ccache for faster builds

### PR DESCRIPTION
**Pull request by thedrow**
Caching is now enabled on all environments.
It should speed up the build significantly.

### CODE REVIEW

**Comment by thedrow** [comment]
Looks like that the build system doesn't use the path. I think it uses CC and CXX instead.
How do we resolve that?

**Comment by thedrow** [comment]
So I got around the build system not recognizing ccache but there's a spec failure on linux now.
Any idea why?

**Comment by brixen** [comment]
@thedrow this build failure on Linux is most likely the issue related to finalization or finalizer thread synchronization that I'm working on so I'm going to merge this.

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious why caching hasn't been enabled before this (i.e., since December 17, 2014, when it became available to open source projects).

Thank you.

**Pull request merged**
