### PR TITLE
If on OS X, check for homebrew-supplied openssl libraries

### PR DESCRIPTION
**Pull request by andre-richter**

### CODE REVIEW

**Comment by YorickPeterse** [comment]
@brixen Leaving this up to you since I _think_ you were discussing something about this. I'm also not a Mac user so I'm not really sure what the context and the likes behind this is.

**Comment by andre-richter** [comment]
Hmm, travis timed out when building a native extension. Doesn't look like it has anything to do with my patch, though.

**Comment by YorickPeterse** [comment]
@andre-richter I restarted the build.

**Comment by brixen** [comment]
@andre-richter thanks for working on this. There's another place we check `@darwin` for the LLVM stuff. It's not critical that you do this, but could you take a little time to standardize both those checks? They are similar and having everything a bit more standard (ie consistent) will help when I port this to Bash soon.

**Comment by brixen** [comment]
@andre-richter thanks!

**Pull request merged**
