### PR TITLE
Codedb ffi io

### PR DESCRIPTION
**Pull request by chuckremes**
Looks like we have a lot of design-in-process inventory (DIP) on this long-lived branch. Need to get this merged soon. :)

### CODE REVIEW

**Comment by chuckremes** [comment]
Converted to codedb-ffi-io branch... this one is very stale.

**Comment by chuckremes** [comment]
Closed in error.

**Comment by chuckremes** [comment]
Outstanding items that need to be completed prior to merge...
(not an exhaustive list yet)

* Pass all rubysl-socket specs on Ubuntu linux. (Already passes all on OS X.)

* Add in locks/mutexes around certain read/seek structures so the class is more reliable when used improperly in multi-threaded situations.

* Remove any dead code still lingering.

* Find any FIXME notations and actually fix them.

* Install and run some C extensions that make use of the C-API IO facilities to confirm everything works as expected. 

* Run MRI IO tests and fix any failures. (This is a big one... I bet there are a bunch of failures since the MRI tests go after a lot of edge cases.)

**Comment by tmornini** [comment]
@chuckremes Wow, this is a huge amount of work! Very cool!

**Comment by chuckremes** [comment]
@tmornini Thanks! It's been a labor of love. :)

**Comment by brixen** [comment]
@chuckremes thank you for the tremendous amount of work here and for the commitment to seeing this through despite the difficulties and the extended period of time it took to work on all the issues.

Any remaining clean up or improvement can happen on master and be sure to take advantage of the ability to tag a release at any time.

**Comment by tmornini** [comment]
WOOHOO! Congrats @chuckremes and @brixen , this is a labor of love!

**Comment by brixen** [comment]
Thanks @tmornini!

**Comment by chuckremes** [comment]
It truly was a labor of love. :)

Now to make it better!

**Pull request merged**
