### PR TITLE
Add experimental support for LLVM 3.6

### PR DESCRIPTION
**Pull request by digitalextremist**
Succeeded in builds in my experience.

@brixen would know better than I would the actual consequences of this.

### CODE REVIEW

**Comment by YorickPeterse** [comment]
A big pile of changes for LLVM 3.6 can already be found in this pull request: https://github.com/rubinius/rubinius/pull/3367/files

Sadly just changing the version to build with isn't enough as LLVM 3.6 removed the old JIT API that we rely on. I'll close this issue in favour of #3367.

**Comment by digitalextremist** [comment]
@YorickPeterse, damn. I thought this was solvable by magic... but alas, it is not. I reverted to `14.04` of Ubuntu while this is sorted out.

**Comment by YorickPeterse** [comment]
@digitalextremist If available you can install a 3.5 version of LLVM (usually distributions keep a few versions around) and use `./configure --llvm-config=llvm-config3.5` (or something similar) to use an older version of LLVM.

**Comment by digitalextremist** [comment]
It'd be great if the `configure` script could detect older versions. I tried to `rvm install rbx` on a fresh `Ubuntu 15.04 x64` install, and it just choked. That's probably a big problem as people migrate to the next distribution of that Linux distribution.

**Comment by jc00ke** [comment]
Yeah, some detection around `llvm-config` (maybe it would fall back to `llvm-config-3.5` then to `llvm-config-3.4`) would be nice.

**Comment by larskanis** [comment]
This worked for me on Ubuntu-15.04:
``` sh
sudo apt-get install llvm-3.5
rvm install rbx-2.5.8 -C --llvm-config=llvm-config-3.5
```

**Pull request closed without merging**
