### PR TITLE
Fix Enumerable#first block arities

### PR DESCRIPTION
**Pull request by kachick**
I guess this fixes https://github.com/rubinius/rubinius/issues/3554

### CODE REVIEW

**Comment by ioquatix** [comment]
Awesome, thanks so much. I guess we should try to evaluate #cycle or any other similar methods (#count?)

**Comment by YorickPeterse** [comment]
Rebased into https://github.com/rubinius/rubinius/compare/87ef3834e9202120a5da088b50a03b04bd304e3e...86bf3170ea8f75911616535ee2659f9666e6b14b, thanks!

> I guess we should try to evaluate #cycle or any other similar methods (#count?)

Yes, but those should go into a separate PR.

**Comment by ioquatix** [comment]
Sure they would be a separate PR, but the Issue which is now closed also raised those points. Should I create a new issue?

**Comment by YorickPeterse** [comment]
@ioquatix If other methods suffer from the same problem then yes, an issue would be appreciated.

**Pull request closed without merging**
