### PR TITLE
Add specs for Method#curry

### PR DESCRIPTION
**Pull request by ruipserra**
This PR adds specs for Method#curry released in ruby 2.2.

### CODE REVIEW

**Comment by YorickPeterse** [comment]
@ruipserra Can you re-submit this PR against the [2.2](https://github.com/rubinius/rubinius/tree/2.2) branch _without_ the `ruby_version_is` guard? We're phasing out Ruby version guards in favour of version specific branches (where applicable).

**Comment by ruipserra** [comment]
@YorickPeterse should I also tag the specs as failing?

**Comment by YorickPeterse** [comment]
@ruipserra If they currently fail, yes.

**Comment by ruipserra** [comment]
Over at #3331

**Pull request closed without merging**
