### PR TITLE
Reworked allocation APIs, STW machinery, and replaced semispace with Immix

### PR DESCRIPTION
**Pull request by brixen**

### CODE REVIEW

**Comment by tak1n** [comment]
Was trying out the branch locally, but was not able to finish the build process: https://gist.github.com/tak1n/1c07de8b853e3d2df631

Its segfaulting on pre_install gems.

**Comment by brixen** [comment]
@tak1n there's a bug in the concurrent marker so you need to run with `export RBXOPT=-Xgc.immix.concurrent=no`. I thought about adding this to .travis.yml (similar to the -Xint in the mcjit branch) but wasn't sure how long I'd have the branch open. I go ahead and add it.

**Comment by brixen** [comment]
@tak1n actually, adding it to .travis.yml won't do anything for you locally. I'll go ahead and disable concurrent marker for now.

**Comment by tak1n** [comment]
@brixen okay, no hurry just was curious and wanted to try it out :smile:

**Pull request merged**
