### PR TITLE
Add a failing spec for a case then protected method called from public_send in own method

### PR DESCRIPTION
**Pull request by kachick**
ref: https://bugs.ruby-lang.org/issues/7499

### CODE REVIEW

**Comment by brixen** [comment]
@kachick thanks for the patch! It's a small thing, but could you please use `lambda` in place of `->` so the specs are consistent.

**Comment by kachick** [comment]
@brixen Sorry, I forgot it 🙇

Adjusted in https://github.com/rubinius/rubinius/pull/3681/commits/10214f2a9083ed2513e810d3a7c19eeab9264220, Thank you!

**Comment by brixen** [comment]
@kachick thank you!

**Comment by kachick** [comment]
😄

**Pull request merged**
