### PR TITLE
Fixes for Alpine Linux

### PR DESCRIPTION
**Pull request by CpuID**
Discussion at https://github.com/rubinius/rubinius/issues/3492

### CODE REVIEW

**Comment by YorickPeterse** [comment]
Only noticed this now, sorry. My only request is to provide a somewhat more meaningful commit message, "fixes so far" doesn't indicate anything about what is actually being fixed. Other than that this PR looks good to me.

**Comment by CpuID** [comment]
@YorickPeterse kind of got it, but that pesky https://github.com/CpuID/rubinius/commit/9dd3f47c6f540ce41053da5478abbfcedd87a5aa is still laying around in the branch... :(

**Comment by YorickPeterse** [comment]
@CpuID A rebase should do it, alternatively I can rebase it prior to merging if that's easier.

**Comment by CpuID** [comment]
yes please, if you can that would be awesome :)

**Comment by YorickPeterse** [comment]
Rebased into 2920c9e0903690f039aa4b6df6059c3c74a4b832, thanks!

**Comment by brixen** [comment]
@CpuID thanks to you and everyone who worked on this. I just built 3.95 on Alpine 3.7 Docker image:

```
/rubinius # bin/rbx -v
rubinius 3.95 (2.3.1 b71836bd 2018-01-25 5.0.0) [x86_64-linux-gnu]
/rubinius # cat /etc/issue
Welcome to Alpine Linux 3.7
Kernel \r on an \m (\l)

/rubinius # uname -a
Linux 11a544638b51 4.9.75-linuxkit-aufs #1 SMP Tue Jan 9 10:58:17 UTC 2018 x86_64 Linux
/rubinius # bin/rbx -S gem list

*** LOCAL GEMS ***

bundler (1.11.2)
minitest (5.11.1)
racc (1.4.14)
rake (12.3.0)
rb-readline (0.5.5)
rdoc (5.1.0)
```

I'm working on a new build pipeline for Rubinius binaries and I'll add Alpine to it.

**Comment by brixen** [comment]
Chicken-scratch notes that need to be turned into a build script https://gist.github.com/brixen/ef849d23078ee3fc617c7f40ad3630bf

**Comment by CpuID** [comment]
> @CpuID thanks to you and everyone who worked on this.

yw :) thanks for sorting it out in the standard version 👍

**Pull request closed without merging**
